steps:  
  #Handle frontend build
  - name: gcr.io/cloud-builders/npm
    entrypoint: npm
    args: ['--prefix', './frontend' ,'install']

  - name: gcr.io/cloud-builders/npm
    entrypoint: npm
    args: ['--prefix', './frontend', 'run', 'build']
    secretEnv: [
      'REACT_APP_MAPS_API_KEY',
      'REACT_APP_FIREBASE_API_KEY',
      'REACT_APP_FIREBASE_AUTH_DOMAIN',
      'REACT_APP_FIREBASE_PROJECT_ID',
      'REACT_APP_FIREBASE_STORAGE_BUCKET',
      'REACT_APP_FIREBASE_MESSAGING_SENDER_ID',
      'REACT_APP_FIREBASE_APP_ID'
    ]

  #Handle the backend build
  - name: gcr.io/cloud-builders/npm
    entrypoint: npm
    args: ['--prefix', './backend' ,'install']
    secretEnv:
      - "G_GEOCODING_API_KEY"


  # Build both frontend and backend
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "client.yaml", "api.yaml"]

availableSecrets:
  secretManager: 
    - versionName: projects/miki-photobook/secrets/REACT_APP_MAPS_API_KEY/versions/latest
      env: 'REACT_APP_MAPS_API_KEY'

    - versionName: projects/miki-photobook/secrets/G_GEOCODING_API_KEY/versions/latest
      env: 'G_GEOCODING_API_KEY'

    - versionName: projects/miki-photobook/secrets/REACT_APP_FIREBASE_API_KEY/versions/latest
      env: 'REACT_APP_FIREBASE_API_KEY'

    - versionName: projects/miki-photobook/secrets/REACT_APP_FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'REACT_APP_FIREBASE_AUTH_DOMAIN'

    - versionName: projects/miki-photobook/secrets/REACT_APP_FIREBASE_PROJECT_ID/versions/latest
      env: 'REACT_APP_FIREBASE_PROJECT_ID'

    - versionName: projects/miki-photobook/secrets/REACT_APP_FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'REACT_APP_FIREBASE_STORAGE_BUCKET'

    - versionName: projects/miki-photobook/secrets/REACT_APP_FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'REACT_APP_FIREBASE_MESSAGING_SENDER_ID'

    - versionName: projects/miki-photobook/secrets/REACT_APP_FIREBASE_APP_ID/versions/latest
      env: 'REACT_APP_FIREBASE_APP_ID'